### ISSUE TITLE
是怎么能做到让用户完全不知道怎么用的

### ISSUE THREAD

**Issue by tangyefei** [ReadSomething/ReadSomething#10]
Chrome插件页面和Github页面都没有任何说明。

Chrome选中内容，右键没有任何可用选项；浏览器头部的设置中没有任何进行设置的位置。

**Comment by zhongyiio** [comment]
感谢反馈，会逐步完善使用文档。您在文章页面点击插件按钮即可进入阅读模式。

**Comment by kk17** [comment]
Yes. Please provide a user guide. You can provide a webpage for a demo. After the user opens this webpage and enables the extension, they can immediately see the effects.
