### ISSUE TITLE
能否放一个  打开/关闭  OpenAI的功能？ 搞不到OpenAi 的key啊

### ISSUE THREAD

**Issue by qqxue** [ReadSomething/ReadSomething#3]
非常感谢开发出了这么好用一个阅读插件，比我以前用过的其他阅读插件好用太多了。。

众所周知，OpenAI目前不对中国地区提供服务，即使好不容易各种渠道搞到一个，很也容易被封。

如果能在设置里，放一个 打开/关闭 OpenAi的选项，就方便太多了。。（希望不会给您增加太多工作量）

**Comment by zhongyiio** [comment]
很好的建议，下个版本加上。
