### ISSUE TITLE
我填写了 OpenAI Key，但仍让我检查 API Key 是否正确

### ISSUE THREAD

**Issue by znlbwo** [ReadSomething/ReadSomething#7]
![image](https://github.com/ReadSomething/ReadSomething/assets/8335856/fa8b9b32-ca6e-4004-994b-4b1b6ec6ae76)

**Comment by zhongyiio** [comment]
这里的错误提示确实有些不合理，目前的实现是所有的异常返回都提示这个信息，后续会改的合理一些。你可以通过浏览器调试窗口，看下 OpenAI API 请求具体的返回，大概率还是 Token 有问题。
